# Generated by Django 6.0.2 on 2026-02-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author_name', models.CharField(max_length=100)),
                ('isbn_no', models.CharField(max_length=13, unique=True)),
                ('published_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pages', models.IntegerField()),
                ('language', models.CharField(max_length=100)),
                ('isAvailable', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
